### ISSUE TITLE
UDP sends 3 commits only even when there are more.

### ISSUE THREAD

**Issue by nixeagle** [danopia/fbi-old#1]
I know this is done to trim flooding, but the IRC bot needs to do the trimming, not the UDP component.

Expected behavior is when 8 commits are sent, all 8 get sent to the commits channel.

**Comment by danopia** [comment]
This will be done as part of rewriting the webhook receiver into pure Thin/ruby.

**Comment by danopia** [comment]
Wow. This is an old bug.
