### ISSUE TITLE
IRC component parses command arguments stupidly

### ISSUE THREAD

**Issue by nixeagle** [danopia/fbi-old#2]
The context here is parsing an IRC command and handling it in another component (eg in irc-command.lisp). This bug was discovered during the course of writing a simple :md5 command for FBI.

The way it is now, we get (command json-publish) which returns the string representing the first argument passed to the bot.... All is fine and dandy.

However, (args json-publish) returns an array of _words_ passed to fbi... _disregarding_ all spaces which prevents commands like :md5 from working correctly. Observe the following command sequence:

   <nixeagle> FBI-1 md5  1

   <FBI-1> c4ca4238a0b923820dcc509a6f75849b

   <nixeagle> FBI-1 md5    1

   <FBI-1> c4ca4238a0b923820dcc509a6f75849b

   <nixeagle> FBI-1 md5   " 1 "

   <FBI-1> 951e27457cf6a25d0d5e06c67f7124c1

   <nixeagle> FBI-1 md5   " 1   "

   <FBI-1> 951e27457cf6a25d0d5e06c67f7124c1

Note that the last command contains two spaces after the 1. Github is eating it for some reason. Note that despite the extra space the md5 hash is the same which is incorrect.

The correct fix is either to hand components the arguments unparsed and allow the components to parse as they see fit, or to treat " ... " as a proper string. I prefer the first option as I can't implement a lisp reader for FBI in the current state.

**Comment by danopia** [comment]
The arg list is provided by ruby's String#split method. I guess that I'll provide arguments as a string to component. Should I also provide a split-up version, or just replace "args" with a string?

**Comment by nixeagle** [comment]
Is the split up form really useful beyond making it easier to do subcommands? It is my personal opinion that _how_ the arguments to a command are processed is the sole responsibility of the component. There is no way the IRC component is going to know how the arguments to a command are going to be used, so don't try... just shove a string at the component (well dump into the channel...) and let _it_ call String#split if it wants to.

Also if you do remove the args form, leave one to two days depreciation time after adding the string version of args before actually removing it. Name the string version of it something else that makes sense. If you don't do this, lisp will barf at you for violating type assumptions... remember this is an incompatible api change.

**Comment by danopia** [comment]
This has been fixed.
